const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const STATUS_VALUES = ["ACTIVE", "SUSPENDED_GAME_ROUND_OVER", "CLOSED"];
const MARKET_STATUS_VALUES = ["RUNNING", "ABANDONED", "STOPPED"];
const RUNNER_STATUS_VALUES = ["IN_PLAY", "LOSER", "TIED_DEAD_HEAT", "WINNER"];

const BetfairTurboHiloRateSchema = new Schema(
  {
    sno: { type: Number, index: true, unique: true },
    evt_id: { type: String, required: false },
    evt_evt: { type: String, required: false },
    evt_od: { type: Date, required: false },
    open_date: { type: Date, required: false },
    cat_mid: { type: String, required: false },
    cat_rnr1: { type: String, required: false },
    cat_rnr2: { type: String, required: false },
    cat_rnr3: { type: String, required: false },
    cat_rnr4: { type: String, required: false },
    cat_rnr5: { type: String, required: false },
    cat_rnr6: { type: String, required: false },
    cat_rnr7: { type: String, required: false },
    cat_rnr8: { type: String, required: false },
    cat_rnr9: { type: String, required: false },
    cat_rnr10: { type: String, required: false },
    cat_rnr11: { type: String, required: false },
    cat_rnr12: { type: String, required: false },
    cat_rnr13: { type: String, required: false },
    cat_rnr14: { type: String, required: false },
    cat_rnr15: { type: String, required: false },
    cat_rnr16: { type: String, required: false },
    cat_sid1: { type: String, required: false },
    cat_sid2: { type: String, required: false },
    cat_sid3: { type: String, required: false },
    cat_sid4: { type: String, required: false },
    cat_sid5: { type: String, required: false },
    cat_sid6: { type: String, required: false },
    cat_sid7: { type: String, required: false },
    cat_sid8: { type: String, required: false },
    cat_sid9: { type: String, required: false },
    cat_sid10: { type: String, required: false },
    cat_sid11: { type: String, required: false },
    cat_sid12: { type: String, required: false },
    cat_sid13: { type: String, required: false },
    cat_sid14: { type: String, required: false },
    cat_sid15: { type: String, required: false },
    cat_sid16: { type: String, required: false },
    evt_status: { type: String, enum: STATUS_VALUES, required: false },
    market_status: { type: String, enum: MARKET_STATUS_VALUES, required: false },
    result: { type: String, required: false },
    rnr1_status: { type: String, enum: RUNNER_STATUS_VALUES, required: false },
    rnr2_status: { type: String, required: false },
    rnr3_status: { type: String, required: false },
    rnr4_status: { type: String, required: false },
    rnr5_status: { type: String, enum: RUNNER_STATUS_VALUES, required: false },
    rnr6_status: { type: String, required: false },
    rnr7_status: { type: String, required: false },
    rnr8_status: { type: String, required: false },
    rnr9_status: { type: String, required: false },
    rnr10_status: { type: String, required: false },
    rnr11_status: { type: String, required: false },
    rnr12_status: { type: String, required: false },
    rnr13_status: { type: String, required: false },
    rnr14_status: { type: String, required: false },
    rnr15_status: { type: String, required: false },
    rnr16_status: { type: String, required: false },
    game_type: { type: Number, required: false },
    left_time: { type: String, required: false },
    stld: { type: Number, default: 0, required: false },
    runner1b1: { type: Number, required: false },
    runner1b2: { type: Number, required: false },
    runner1b3: { type: Number, required: false },
    runner1l1: { type: Number, required: false },
    runner1l2: { type: Number, required: false },
    runner1l3: { type: Number, required: false },
    runner2b1: { type: Number, required: false },
    runner2b2: { type: Number, required: false },
    runner2b3: { type: Number, required: false },
    runner2l1: { type: Number, required: false },
    runner2l2: { type: Number, required: false },
    runner2l3: { type: Number, required: false },
    cards_desc: { type: String, required: false },
    suspend1: { type: Number, required: false },
    suspend2: { type: Number, required: false },
    suspend3: { type: Number, required: false },
    suspend4: { type: Number, required: false },
    suspend5: { type: Number, required: false },
    suspend6: { type: Number, required: false },
    suspend7: { type: Number, required: false },
    suspend8: { type: Number, required: false },
    suspend9: { type: Number, required: false },
    suspend10: { type: Number, required: false },
    suspend11: { type: Number, required: false },
    suspend12: { type: Number, required: false },
    suspend13: { type: Number, required: false },
    suspend14: { type: Number, required: false },
    suspend15: { type: Number, required: false },
    suspend16: { type: Number, required: false },
    update_at: { type: Date, default: Date.now, required: false },
    counter: { type: Number, default: 0, required: false },
    diamond_id: { type: String, required: false },
    round: { type: Number, default: 0, required: false },
    time: { type: String, required: false },
    time_percentage: { type: String, required: false },
    round_od: { type: Date, required: false },
    round_close_date: { type: Date, required: false },
    prediction: { type: String, required: false },
    market_id1: { type: String, required: false },
    market_id2: { type: String, required: false },
    is_bet_place: { type: Number, default: 0, required: false }
  },
  {
    collection: "bz_betfair_turbo_hilo_rates",
    versionKey: false
  }
);

BetfairTurboHiloRateSchema.index({ evt_id: 1 });
BetfairTurboHiloRateSchema.index({ evt_od: 1 });
BetfairTurboHiloRateSchema.index({ cat_mid: 1 });
BetfairTurboHiloRateSchema.index({ evt_status: 1 });
BetfairTurboHiloRateSchema.index({ game_type: 1 });
BetfairTurboHiloRateSchema.index({ evt_status: 1, stld: 1 });

module.exports = mongoose.model("BzBetfairTurboHiloRate", BetfairTurboHiloRateSchema);